name: Build and Push Proxify Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set build time
        run: echo "BUILDTIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Read version from version.go
        id: version
        run: |
          VERSION=$(grep -E 'const Version = ' version.go | sed -E 's/.*"(.+)".*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            madwind/proxify:latest
            madwind/proxify:${{ env.VERSION }}
          build-args: |
            BUILDTIME=${{ env.BUILDTIME }}
            TARGETOS=linux
            TARGETARCH=amd64
